-- $Id$

CREATE TABLE newsgroups (
  id INTEGER UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(200) NOT NULL,
  UNIQUE(name)
);

CREATE TABLE authors (
  id INTEGER UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(200) NOT NULL,
  UNIQUE(name)
);

CREATE TABLE articles (
  id BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  postid INTEGER UNSIGNED NOT NULL,
  subject VARCHAR(2000) NOT NULL,
  authorid INTEGER UNSIGNED NOT NULL,
  size INTEGER UNSIGNED NOT NULL,
  parts_total SMALLINT UNSIGNED NOT NULL,
  parts_found SMALLINT UNSIGNED NOT NULL,
  parts MEDIUMBLOB NOT NULL,
  post_date INTEGER UNSIGNED NOT NULL,
  created INTEGER UNSIGNED NOT NULL,
  updated INTEGER UNSIGNED NOT NULL,
  INDEX(postid),
  INDEX(subject(100),authorid,post_date),
  INDEX(authorid),
  INDEX(created)
);

CREATE TABLE articlegroup (
  articleid BIGINT UNSIGNED NOT NULL,
  groupid INTEGER UNSIGNED NOT NULL,
  created INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(articleid,groupid),
  INDEX(groupid,created)
);

CREATE TABLE servergroup (
  serverid INTEGER UNSIGNED NOT NULL,
  groupid INTEGER UNSIGNED NOT NULL,
  last BIGINT UNSIGNED NOT NULL,
  checked_date INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(serverid,groupid)
);
